### ISSUE TITLE
Ignore *.bs.js files?

### ISSUE THREAD

**Issue by emmenko** [glennsl/bs-typed-glamor#2]
This is more of a nitpick, but I noticed that the `*.bs.js` files are in version control. Is it on purpose or should we ignore them?

**Comment by glennsl** [comment]
It's kind of on purpose, to be able to inspect the code generated when PRs are submitted, and to diff changes coming from new bs-platform versions and such. In practice I don't really use it much though, and am moving away from it in other repos, so ignore them if you want to.

**Comment by emmenko** [comment]
I see...well I don't have a strong opinion on this. Do you recommend in general to have the generated code in version control to be able to inspect it? Or, isn't causing too much noise?

**Comment by glennsl** [comment]
I'd probably recommend against it  now, though I don't think the noise it causes is too bad. It's just not as useful as I originally imagined it would be.

I'll close this and probably revisit later. It's not like there's a lack of reminders that they're checked in at least ;)
