### ISSUE TITLE
Transform the labelled functions into unlabelled to ease their consumption from PPX

### ISSUE THREAD

**Issue by jchavarri** [glennsl/bs-typed-glamor#6]
I'm using `bs-typed-glamor` together with https://github.com/astrada/ppx_bs_css, which honestly provides a pretty amazing dev exp. Huge thanks to both @glennsl and @astrada :)

I found that when defining a property like `padding: 2px 4px 3px 1px` it gets translated by the ppx to `padding4(px(2), px(4), px(3), px(1))`, which compiles fine, but you get the warning `labels were omitted in the application of this function.`

I wonder if there would be a chance to update these labelled functions to not use labels (breaking change, I know) and, if there's a will to keep the labelled functions, rename them to some alternate name, like `padding4L`.

I'd be willing to work on this if the proposal makes sense.

**Comment by glennsl** [comment]
Oh, nice, I was not aware of the ppx, but that looks awesome. It does seem to have limited utility if it doesn't allow control structures though. Static typing for a logic-less declarative visual DSL wouldn't catch many errors. It's only when you introduce logic that you might start making errors that aren't immediately apparent. Perhaps it's posible to do the logic up front and assign the result to variables that can then be used in the ppx though?

Anyway, I'd rather not bloat the API with an additional set of functions, and I don't want to remove the labels either since I think they're very useful without the ppx. I would much prefer if the ppx special-cased these properties to add labels to them.

**Comment by jchavarri** [comment]
> Perhaps it's posible to do the logic up front and assign the result to variables that can then be used in the ppx

Yes, you can add logic outside the ppx as you mention. Something like this works:

```reason
let myStyle = isEmpty => {
  open TypedGlamor;
  let bkgColor = isEmpty ? red : blue;
  %style
  {typed|
    background-color: bkgColor;
  |typed};
};
```

Maybe in the future, something like es6 template strings `${}` placeholders could be added?

For me however, most of the value comes from being able to use the syntax I know already. Learning Glamor API (or any other), or the bindings to Glamor, is a large investment with little ROI to me, as I might move from one lib to the next, the owner might change the API over time etc. But the CSS syntax will remain fairly constant and well documented. This has been kind of proven with styled-components in JS-land...

> I would much prefer if the ppx special-cased these properties to add labels to them.

How could the PPX do this without adding some tightly coupling with TypedGlamor? Seems each function has different label names, and also there are some inconsistencies or edge cases that the ppx would need to know about: `v`/`h` vs `top`/`bottom`, labels only added with 2+params, color functions have no labels...

> Anyway, I'd rather not bloat the API with an additional set of functions, and I don't want to remove the labels either since I think they're very useful without the ppx.

👍

**Comment by astrada** [comment]
> How could the PPX do this without adding some tightly coupling with TypedGlamor?

It's not a big deal, actually. I already have lots of special cases to handle shorthand properties (like `border`) as CSS grammar is very liberal :wink: . Feel free to open an issue on my repo.

**Comment by glennsl** [comment]
> Maybe in the future, something like es6 template strings ${} placeholders could be added?

That would be really cool, but just defining variables up front is a pretty good solution for now. The bigger problem, I think, is how you'd switch between sets of declarations. But definitely an interesting area to explore going forward.

> For me however, most of the value comes from being able to use the syntax I know already.

Definitely, that's a big factor for me as well. But if you take out (most of) the ability to integrate with the "host" language, why not just use css modules instead?

> How could the PPX do this without adding some tightly coupling with TypedGlamor?

Technically it would be tightly coupled with `bs-typed-css-core`, not `bs-typed-glamor`, and is the reason why the former exists. Also an idea blatantly stolen from @astrada's [`bs-css-core`](https://github.com/astrada/bs-css-core) btw

**Comment by jchavarri** [comment]
> how you'd switch between sets of declarations

What prevents you from switching between sets of declarations with a similar example to the one mentioned above?

> But if you take out (most of) the ability to integrate with the "host" language, why not just use css modules instead?

The PPX allows to (when compared to CSS modules):
- colocate the styles in the same file as the component
- type check the properties _and_ values: I'm the worst at CSS ✌️  so any help from the compiler is always welcomed, but maybe this is a non-issue for people that keep a healthier relationship with CSS

**Comment by glennsl** [comment]
> What prevents you from switching between sets of declarations with a similar example to the one mentioned above?

Consider something like [this](https://github.com/rebench/rebench.github.io/blob/master/src/common/components/BlockStyles.ml#L11-L18):

```ml
  if isCollapsible then
    select "& > header" [
      hover [
        background Colors.panelDark;
        cursor pointer;
      ];
    ]
else select "&" [];
```
I'm not sure how you'd accomplish that with just variables. You could duplicate the entire style for each state, but with a few more state variables that turns into a complicated mess real quick.

> The PPX allows to (when compared to CSS modules):
> * colocate the styles in the same file as the component

True. I think I prefer to have CSS in a separate file though, as long as it's split per component and located side-by-side.

> * type check the properties and values: I'm the worst at CSS so any help from the compiler is always welcomed, but maybe this is a non-issue for people that keep a healthier relationship with CSS

A good IDE will give you autocomplete for CSS. This won't, though I'm sure it's not too hard to get a similar kind of autocomplete for an embedded language. Also syntax highlighting.

Typos don't seem significant enough to benefit much from type checking either, as CSS describes visuals where you'll easily be able to observe that the result is not as expected. At least in my experience.

But if you introduce logic the equation changes, of course.
